# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    schedule:
      # Check for updates to Gradle dependencies every day
      interval: "daily"
    commit-message:
      prefix: deps(upgrade)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every day
      interval: "daily"
    commit-message:
      prefix: deps(upgrade)
