version: '3'
services:
  serve:
    image: squidfunk/mkdocs-material:9
    volumes:
      - ./:/docs
      - ./site:/site
    ports:
      - 8000:8000

  build:
    image: squidfunk/mkdocs-material:9
    volumes:
      - ./:/docs
      - ./site:/site
    command: build --clean
