name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '22'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml
