name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup JDK 22
        uses: actions/setup-java@v5
        with:
          cache: 'maven'
          distribution: 'temurin'
          java-version: '22'

      - name: Build with Maven
        run: ./mvnw -B clean package

      - name: Check if version is a SNAPSHOT
        if: github.event_name == 'push'
        id: check_snapshot
        run: |
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $VERSION"
          if [[ "$VERSION" == *-SNAPSHOT ]]; then
            echo "is_snapshot=true" >> $GITHUB_OUTPUT
          else
            echo "is_snapshot=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish Snapshot to GitHub Packages
        if: github.event_name == 'push' && steps.check_snapshot.outputs.is_snapshot == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./mvnw -s ./.github/settings.xml -B deploy -DskipTests=true
