name: Publish Snapshot

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup JDK 22
        uses: actions/setup-java@v5
        with:
          cache: 'maven'
          distribution: 'temurin'
          java-version: '22'

      - name: Check if version is a SNAPSHOT
        id: check_snapshot
        run: |
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $VERSION"
          if [[ "$VERSION" == *-SNAPSHOT ]]; then
            echo "is_snapshot=true" >> $GITHUB_OUTPUT
          else
            echo "is_snapshot=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to GitHub Packages
        if: steps.check_snapshot.outputs.is_snapshot == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./mvnw -s ./.github/settings.xml -B clean deploy -DskipTests=true
